# Generated by Django 5.0 on 2023-12-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image1',
        ),
    ]
